version: '3'


services:
    app:
      build: .
      container_name: turi-app
      command: bash docker-entrypoint.sh
      volumes:
        - .:/home/django/app
      ports:
        - "8002:8002"
      depends_on:
        - db

    db:
      image: postgres
      container_name: turi
      tty:  true
      ports:
        - "5433:5432"
      environment:
        - POSTGRES_DB=turi
        - POSRGRES_USER=postgres
        - POSTGRES_PASSWORD=root
      volumes:
        - turi:/var/lib/postgresql/data
    
volumes:
  turi:
    external: true
  