# Generated by Django 3.0.6 on 2020-09-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge_reg', '0002_auto_20200927_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrojuridico',
            name='ementa',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='registrojuridico',
            name='favor_contribuinte',
            field=models.CharField(choices=[('0', 'Contrário ao Cliente'), ('1', 'Parcialmente Favorável'), ('2', 'Favorável ao Cliente')], db_index=True, max_length=2),
        ),
    ]
