# Generated by Django 3.0.6 on 2020-09-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge_reg', '0003_auto_20200927_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrojuridico',
            name='id_cliente',
            field=models.IntegerField(db_index=True),
        ),
    ]
